### PR TITLE
an example for the manual UTE teach

### PR DESCRIPTION
**Pull request by Alaric84**
example script to do the UTE teach in as discussed in #60 
thanks a lot to @Holger-Will

### CODE REVIEW

**Comment by Holger-Will** [comment]
This pull request **introduces 1 alert** when merging a1d485f8d19b3e08c0a4f404ff1027efc3c070c0 into 0905a7246d44a9a102760596611763be157261d0 - [view on LGTM.com](https://lgtm.com/projects/g/enocean-js/enocean-js/rev/pr-bae910d56545ab06fa932737213f22c9c0df95a9)

**new alerts:**

* 1 for Expression has no effect

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Alaric84** [comment]
hm - ok I fixed the "expression without effect" but I have no clue how I broke the CI

**Comment by Holger-Will** [comment]
i use https://standardjs.com/ as linter ;-)
do `npm run fix` and you are good to go.
you can check with `npm test` to check if everything is in order...

**Comment by Alaric84** [comment]
finally ...
living in a fully integrated world of VisualStudio-TFS-ReSharper-SonarQube this seams to be quite some handicraft ;-)

**Comment by Holger-Will** [comment]
i think all examples should use the same port for consistencies sake. maybe even with variable...

```
var portname = '/dev/ttyUSB0' 
// enoceanPi
// var portname = '/dev/ttyAMA0 ' 
// Windows
// var portname = 'COM0 ' 
const port = new SerialPort(portname, { baudRate: 57600 })
```

something like that... we can do this later, just thinking aloud ;-)

**Comment by Holger-Will** [comment]
thanks!

**Pull request merged**
